# Generated by Django 4.2.1 on 2023-05-22 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('name', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Usr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256, null=True)),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('source_name', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('rate', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.company')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usr')),
            ],
        ),
        migrations.CreateModel(
            name='Analyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('avg_rating', models.ImageField(blank=True, null=True, upload_to='analyze')),
                ('rating_distribution', models.ImageField(blank=True, null=True, upload_to='analyze')),
                ('num_reviews_month', models.ImageField(blank=True, null=True, upload_to='analyze')),
                ('num_reviews_country', models.ImageField(blank=True, null=True, upload_to='analyze')),
                ('rating_share_country', models.ImageField(blank=True, null=True, upload_to='analyze')),
                ('bigrams_bad_grades', models.ImageField(blank=True, null=True, upload_to='analyze')),
                ('bigrams_good_grades', models.ImageField(blank=True, null=True, upload_to='analyze')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
